swagger: "2.0"
info:
  title: "Bank Argent API documentation"
  description: "Contains all available API endpoints in this codebase"
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /user/login:
    post:
      tags:
        - "User Module"
      summary: "To Login"
      description: "Endpoint for Login"
      parameters:
        - in: "body"
          name: "body"
          description: "Login Payload"
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Login Successfully"
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: "Invalid Fields"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/signup:
    post:
      tags:
        - "User Module"
      summary: "To Signup"
      description: "Endpoint for Signup"
      parameters:
        - in: "body"
          name: "body"
          description: "Signup Payload"
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Signup Successfully"
          schema:
            $ref: "#/definitions/ProfileResponse"
        "400":
          description: "Invalid Fields"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - "User Module"
      summary: "To fetch a user profile"
      description: "Endpoint for fetching a user profile"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        "200":
          description: "User profile retrieved successfully"
          schema:
            $ref: "#/definitions/ProfileResponse"
        "400":
          description: "Invalid Fields"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      security:
        - Bearer: []
      tags:
        - "User Module"
      summary: "To update a user profile"
      description: "Endpoint for updating a user profile"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Update user profile attributes"
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - "application/json"
      responses:
        "200":
          description: "User profile updated successfully"
          schema:
            $ref: "#/definitions/ProfileResponse"
        "400":
          description: "Invalid Fields"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "To fetch a user transactions"
      description: "Endpoint for fetching a user transactions"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transactions retrieved successfully"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "To fetch a user transaction details by ID"
      description: "Endpoint for fetching a user transactions"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "ID of a transaction"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transactions retrieved successfully"
          schema:
            $ref: "#/definitions/TransactionResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/transaction/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "To update a user transaction category by ID"
      description: "Endpoint for updating a user transaction category"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "ID of a transaction"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Update a user transaction attribute"
          required: true
          schema:
            $ref: "#/definitions/TransactionCategory"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transaction category updated successfully"
          schema:
            $ref: "#/definitions/TransactionResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /user/transaction/{transactionId}/notes:
    post:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "To add a user transaction notes by ID"
      description: "Endpoint for adding a user transaction notes"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "ID of a transaction"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Add a user transaction notes"
          required: true
          schema:
            $ref: "#/definitions/TransactionNotes"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transaction notes added successfully"
          schema:
            $ref: "#/definitions/TransactionResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "To update a user transaction notes by ID"
      description: "Endpoint for updating a user transaction notes"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "ID of a transaction"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Update a user transaction notes"
          required: true
          schema:
            $ref: "#/definitions/TransactionNotes"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transaction notes added successfully"
          schema:
            $ref: "#/definitions/TransactionResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "To delete a user transaction notes by ID"
      description: "Endpoint for deleting a user transaction notes"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "ID of a transaction"
          required: true
          type: "integer"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Update a user transaction notes"
          required: true
          schema:
            $ref: "#/definitions/TransactionNotes"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transaction notes deleted successfully"
          schema:
            $ref: "#/definitions/TransactionResponse"
        "401":
          description: "JWT expired"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  User:
    properties:
      email:
        type: "string"
        description: "user email"
      password:
        type: "string"
        description: "user password"
      firstName:
        type: "string"
        description: "user first name"
      lastName:
        type: "string"
        description: "user last name"
  Login:
    properties:
      email:
        type: "string"
        description: "user email"
      password:
        type: "string"
        description: "user password"
  ProfileResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
      body:
        type: "object"
        properties:
          email:
            type: "string"
          firstName:
            type: "string"
          lastName:
            type: "string"
          createdAt:
            type: "string"
          updatedAt:
            type: "string"
          id:
            type: "string"
  LoginResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
      body:
        type: "object"
        properties:
          token:
            type: "string"
  TransactionsResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
      body:
        type: "object"
        properties:
          account:
            type: "object"
            properties:
              accountId:
                type: "integer"
              accountRef:
                type: "string"
              title:
                type: "string"
              description:
                type: "string"
              previousBalance:
                type: "number"
          transactions:
            type: "array"
            items:
              $ref: "#/definitions/Transaction"
  TransactionResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
      body:
        type: "object"
        $ref: "#/definitions/Transaction"
  Transaction:
    type: "object"
    properties:
      transactionId:
        type: "integer"
      date:
        type: "string"
        format: "date-time"
      description:
        type: "string"
      amount:
        type: "number"
      balance:
        type: "number"
      transactionType:
        type: "string"
      category:
        type: "string"
      notes:
        type: "string"
  TransactionCategory:
    type: "object"
    properties:
      category:
        type: "string"
  TransactionNotes:
    type: "object"
    properties:
      notes:
        type: "string"
  ErrorResponse:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"
  UserProfile:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
